CREATE TABLE IF NOT EXISTS usuarios (
id SERIAL PRIMARY KEY,
nome_completo VARCHAR(255) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
senha_hash VARCHAR(255) NOT NULL,
data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cargos (
id SERIAL PRIMARY KEY,
nome VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS usuario_cargo (
usuario_id INT NOT NULL,
cargo_id INT NOT NULL,
PRIMARY KEY (usuario_id, cargo_id),
FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
FOREIGN KEY (cargo_id) REFERENCES cargos(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS tokens (
id SERIAL PRIMARY KEY,
token VARCHAR(255) UNIQUE NOT NULL,
usado BOOLEAN DEFAULT FALSE,
data_geracao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
